"'Screen Configuration' As screen":

    Container1_2 As groupContainer.verticalAutoLayoutContainer:
        Height: =Parent.Height
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        Width: =Parent.Width
        ZIndex: =1

        HeaderCMP_withoutNavbar_3 As HeaderCMP_withoutNavbar:
            Height: =Parent.Height*.1
            LayoutMinHeight: =640
            LayoutMinWidth: =640
            Width: =Parent.Width

        Container29 As groupContainer.manualLayoutContainer:
            AlignInContainer: =AlignInContainer.Center
            FillPortions: =0
            Height: =Parent.Height*.9
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            Width: =Parent.Width
            ZIndex: =2

            ConMain_ConfigurationsScreen As groupContainer.verticalAutoLayoutContainer:
                DropShadow: =DropShadow.Bold
                Fill: =ColorFade(RGBA(107, 29, 94,1),96%)
                Height: =Parent.Height*.85
                LayoutAlignItems: =LayoutAlignItems.Center
                LayoutDirection: =LayoutDirection.Vertical
                LayoutMode: =LayoutMode.Auto
                Width: =Parent.Width*.85
                X: =Parent.Width/2-Self.Width/2
                Y: =Parent.Height/2-Self.Height/2
                ZIndex: =2

                ConUpperPart As groupContainer.horizontalAutoLayoutContainer:
                    AlignInContainer: =AlignInContainer.SetByContainer
                    DropShadow: =DropShadow.None
                    FillPortions: =0
                    Height: =Parent.Height*.35
                    LayoutAlignItems: =LayoutAlignItems.Center
                    LayoutGap: =20
                    LayoutJustifyContent: =LayoutJustifyContent.Center
                    LayoutMinHeight: =100
                    LayoutMinWidth: =250
                    LayoutMode: =LayoutMode.Auto
                    Width: =Parent.Width
                    ZIndex: =1

                    ConCard_defaultValues As groupContainer.verticalAutoLayoutContainer:
                        AlignInContainer: =AlignInContainer.Center
                        DropShadow: =DropShadow.Semibold
                        Fill: =RGBA(255, 255, 255, 1)
                        FillPortions: =0
                        Height: =Parent.Height*.6
                        LayoutDirection: =LayoutDirection.Vertical
                        LayoutMinHeight: =
                        LayoutMinWidth: =250
                        LayoutMode: =LayoutMode.Auto
                        Width: =Parent.Width*.3
                        ZIndex: =1

                        "'Card compomnent_3' As 'Card compomnent'":
                            Height: =Parent.Height
                            image: =partnership
                            LayoutMinHeight: =640
                            LayoutMinWidth: =640
                            MainText: ="Manage default values"
                            SecondaryText: ="Manage the default values of your vendor"
                            Width: =Parent.Width

                    "'ConCard_Terms&Conditions' As groupContainer.verticalAutoLayoutContainer":
                        AlignInContainer: =AlignInContainer.SetByContainer
                        DropShadow: =DropShadow.Semibold
                        Fill: =RGBA(255, 255, 255, 1)
                        FillPortions: =0
                        Height: =Parent.Height*.6
                        LayoutDirection: =LayoutDirection.Vertical
                        LayoutMinHeight: =100
                        LayoutMinWidth: =250
                        LayoutMode: =LayoutMode.Auto
                        Width: =Parent.Width*.3
                        ZIndex: =2

                        "'Card compomnent_2' As 'Card compomnent'":
                            Height: =Parent.Height
                            image: =goal
                            LayoutMinHeight: =640
                            LayoutMinWidth: =640
                            MainText: ="Manage Supplier T&C"
                            SecondaryText: ="Manage terms & conditions documents for each supplier"
                            Width: =Parent.Width

                    ConCard_FieldAssgnment As groupContainer.verticalAutoLayoutContainer:
                        AlignInContainer: =AlignInContainer.SetByContainer
                        DropShadow: =DropShadow.Semibold
                        Fill: =RGBA(255, 255, 255, 1)
                        FillPortions: =0
                        Height: =Parent.Height*.6
                        LayoutDirection: =LayoutDirection.Vertical
                        LayoutMinHeight: =100
                        LayoutMinWidth: =250
                        LayoutMode: =LayoutMode.Auto
                        Width: =Parent.Width*.3
                        ZIndex: =3

                        "'Card compomnent_1' As 'Card compomnent'":
                            Height: =Parent.Height
                            image: =database
                            LayoutMinHeight: =640
                            LayoutMinWidth: =640
                            MainText: ="Manage Field Assignment"
                            SecondaryText: ="Describe Who can edit Which Field"
                            Width: =Parent.Width

