"'Screen Configuration' As screen":

    Container1_2 As groupContainer.verticalAutoLayoutContainer:
        Height: =Parent.Height
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        Width: =Parent.Width
        ZIndex: =1

        HeaderComponent_3 As HeaderComponent:
            CurrentScreen: ="CONFIGURATIONS"
            Height: =Parent.Height*.1
            LayoutMinHeight: =640
            LayoutMinWidth: =640
            NavItems: =NavBar

