"'Screen Configuration' As screen":

    Container1_2 As groupContainer.verticalAutoLayoutContainer:
        Height: =Parent.Height
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        Width: =Parent.Width
        ZIndex: =1

        HeaderComponent_3 As HeaderComponent:
            CurrentScreen: ="Screen Configuration"
            Height: =Parent.Height*.1
            LayoutMinHeight: =640
            LayoutMinWidth: =640
            NavItems: =NavBar

        Container4_3 As groupContainer.verticalAutoLayoutContainer:
            AlignInContainer: =AlignInContainer.Center
            FillPortions: =0
            Height: =Parent.Height*.9
            LayoutDirection: =LayoutDirection.Vertical
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            Width: =Parent.Width
            ZIndex: =2

